title: Jeremy Mumford
logo: "/images/logo.png?raw=true" 
bio: AI Software Engineer | Optimist | Outdoor Enthusiast
description: Jeremy is an experienced programmer specializing in software and data engineering with a focus on AI. His expertise lies in creating integrated data and software solutions. He began programming in high school and holds a degree in Computer Science with a concentration in Data Science, and minors in Statistics and Business. Jeremy has developed his skills in startups, creating essential business software. Currently, at Pattern, he is a key contributor to the AI team, utilizing generative AI to enhance company productivity and output significantly.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-5HX2090PDD 
