title: Jeremy Mumford
logo: "/images/logo.png?raw=true" 
bio: AI Engineer (someone who builds like a software engineer but thinks like a data scientist)
description: Howdy! I'm Jeremy. I love building things. I studied a lot of statistics and machine learning in school, but realized I prefer software engineering after my first couple of jobs. After the ChatGPT moment, I realized I could combine my skills with my knowledge. Now, I lead the AI engineering team at Pattern, where we innovate and create new AI powered products while also building a core AI foundation that the rest of the company can build on. I'm good with software engineering and architecting, great with AI, decent with data, ok at DevOps, and terrible with frontend design.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-5HX2090PDD 
